<?php

$modversion['name'] = _MI_CLA_NAME;
$modversion['version'] = '2.04';
$modversion['description'] = _MI_CLA_DESC;
$modversion['credits'] = "Pascal Le Boustouller / redesigned by glassJAw and <a href='mailto:jojup@neumaerker.net'>jojup</a> from myxoops.de team";
$modversion['author'] = "Tom<br><a href='http://malaika.s31.xrea.com/'>Malaika System</a>";
$modversion['license'] = 'GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/myads.jpg';
$modversion['dirname'] = 'myads';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Templates
$modversion['templates'][1]['file'] = 'myads_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'myads_adlist.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'myads_category.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'myads_item.html';
$modversion['templates'][4]['description'] = '';

// Blocks
$modversion['blocks'][1]['file'] = 'annonces.php';
$modversion['blocks'][1]['name'] = _MI_CLA_NAME;
$modversion['blocks'][1]['description'] = 'Shows new annonces';
$modversion['blocks'][1]['show_func'] = 'annonces_show';
$modversion['blocks'][1]['template'] = 'myads_block_new.html';

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'ann_annonces';
$modversion['tables'][1] = 'ann_categories';
$modversion['tables'][2] = 'ann_type';
$modversion['tables'][3] = 'ann_prix';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'ann_search';
